--- # Open the ProfanityFilter CI at https://poggit.pmmp.io/ci/xqwtxon/ProfanityFilter
build-by-default: true
branches:
- main
projects:
  ProfanityFilter:
    lint: false
    path: ""
    icon: "ProfanityFilter.png"
...
