--- # Open the HiveProfanityFilter CI at https://poggit.pmmp.io/ci/xqwtxon/HiveProfanityFilter
build-by-default: true
branches:
- main
projects:
  HiveProfanityFilter:
    path: ""
libs:
   - src: jojoe77777/FormAPI/libFormAPI
     version: ^2.1.0
...
