---
name: HiveProfanityFilter
version: 0.0.3-BETA
main: xqwtxon\HiveProfanityFilter\Loader
api: 4.0.0
src-namespace-prefix: xqwtxon\HiveProfanityFilter
description: "A best hive profanity filter for pocketmine. Controls hate speech and blocks bad words in certain on the chat."
website: "https://github.com/xqwtxon/HiveProfanityFilter"
authors: 
- "xqwtxon"
- "z3nXxz"
permissions:
      profanity.command:
           description: ProfanityFilter Operator Permission
           default: op
libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: 2.1.0
depend: [InfoAPI,GroupsAPI]
...
