---
# Hive Profanity Filter
# A hive profanity best filter. A utility that controls swearing and hate speech.

# Profanity Type
# Options: "hide","block","block-with-message"
# Check https://github.com/xqwtxon/HiveProfanityFilter/blob/main/ProfanityType.md for more information about profanity types.
type: "block-with-message"

# If "block-with-message" has selected, you can add your own message right here.
block-message: "§cHey, Watch your Language!"

# Plugin Languages
# You can make your own plugin language by option: "custom"
# and make file custom.yml in languages/ folder in plugin_data/HiveProfanityFilter/
# You can make your own pull request for more languages.
lang: "en-us"



# Configuration Version
# Please dont change this, change this IF YOU KNOW WHAT ARE YOU DOING!
config-version: "0.0.2"
...