---
# Hive Profanity Filter
# A hive profanity best filter. A utility that controls swearing and hate speech.
# It is licensed on CC-BY-NC-SA by Creative Commons
# Copyright (c) by @xqwtxon

# Profanity Type
# Options: "hide","block","block-with-message"
# Check https://github.com/xqwtxon/HiveProfanityFilter/blob/main/ProfanityType.md 
# for more information about profanity types.
type: "block-with-message"

# If "block-with-message" has selected, you can add your own message right here.
block-message: §cHey, Watch your Language!

# Plugin Languages
# You can make your own plugin language by option: "custom"
# and make file custom.yml in languages/ folder in plugin_data/HiveProfanityFilter/
# You can make your own pull request for more languages.
lang: en-us

# Max Violation
# Player Violation Punishment
# If player reached max violations. It will be?
# Options: kick,ban
punishment-type: kick
# If player reached max violations will be kicked.
# You can set max player violations here. 
# When player is kicked. The player violations will reset.
max-violations: 5
# Kick Violation Message
# However it cool if theres a message will leaved if player
# violates.
kick-message: You have been kicked for reason 'Profanity'.




# Configuration Version
# Please dont change this, change this IF YOU KNOW WHAT ARE YOU DOING!
config-version: 0.0.3
...