name: Plugin CI

on:
  # Schedule updates (every 1 hour and 30 minutes)
  schedule: [{cron: "30 1 * * *"}]
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Plugin Security Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.0.19"

    steps:
      - name: Action Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: pmmp/setup-php-action@247e08acd52c1465f8f144c162c88f079d8c1174
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"
      - name: Install PHPStan Composer dependencies
        working-directory: ./phpstan
        run: composer install --prefer-dist --no-interaction
      - name: PHP-CS-FIXER
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --show-progress=estimating
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.1
        with:
          add: '.'
          message: 'Fix CS'
          push: true
      - name: Run PHPStan
        working-directory: ./phpstan
        run: vendor/bin/phpstan analyze
      - name: Complete the job!
        run: |
          echo The job was successful.
          echo Removing all files...
          rm -rf ./*
          echo Time Successful:
          time
          echo Done! The job was successful removed all files in current working directory.
      
